[tox]
requires =
    tox ~= 4.53.1
env_list = ruffregression, ruff, mypy, pytest, build, black

[testenv:ruff]
description = run ruff linting
basepython = py314
deps =
    ruff ~= 0.15.12
extras = typed
commands = ruff check --ignore=C90,N,D,UP,ANN,BLE,A,T20,SIM,PTH,TD,ERA,PL,TRY,RUF,E722,ARG002,S110,S112,F401,FBT .

[testenv:black]
description = run black formatter
basepython = py314
deps =
    black ~= 26.3.1
commands = black --check .

[testenv:mypy]
description = run mypy type checking
basepython = py314
deps =
    mypy ~= 1.20.2
    pytest ~= 9.0.3
extras = typed
commands = mypy --disable-error-code=no-untyped-call --disable-error-code=no-untyped-def .

[testenv:pytest]
description = run unit tests
basepython = py314
deps =
    pytest ~= 9.0.3
# test_import.py must be tested separately, as it requires to import pysweepme at the exact moment
commands =
    pytest tests/test_import.py
    pytest tests --ignore tests/test_import.py

[testenv:ruffregression]
description = compare strict ruff failures to master
basepython = py314
deps =
    ruff ~= 0.15.12
allowlist_externals = git, cmd
extras = typed
commands =
    cmd /c "(if exist .reference rmdir /S /Q .reference) && mkdir .reference"
    git fetch origin main
    git --work-tree=.reference restore --source=origin/main -- .
    cmd /c "cd .reference && python -m venv .venv && .venv\Scripts\activate.bat && python -m pip install -e .[dev,typed]"
    cmd /c "copy pyproject.toml .reference\pyproject.toml"
    cmd /c "cd .reference && .venv\Scripts\activate.bat && ruff check --output-format=json . > ..\ref.json & exit 0"
    cmd /c "ruff check --output-format=json . > ruff.json & exit 0"
    python .github\compare_ruff_output.py

[testenv:build]
description = create pysweepme wheel
basepython = py314
skip_install = True
deps =
    build ~= 1.5.0
commands = python -m build --wheel