name: Check Semilinear History

on: 
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  semilinear_history:
    name: Check Semilinear History
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Semilinear History
      shell: pwsh
      run: |
        .\.github\Check-SemilinearHistory.ps1 -targetBranch ${{ github.base_ref }} -sourceBranch ${{ github.head_ref }}
