name: Run Checks

on: 
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  checks:
    name: Run Checks
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox~=4.6.1
    - name: Run tox
      run: |
        tox run-parallel
